Make mkt alias use mkproject with a prefix

diff --git a/bin/mkproject b/bin/mkproject
--- a/bin/mkproject
+++ b/bin/mkproject
@@ -2,18 +2,24 @@
 
 set -e
 
-while getopts "n" opt; do
+while getopts "nt" opt; do
   case "$opt" in
     n)
       npm_init=true
       ;;
+    t)
+      tmp_prefix=tmp-$(date +%F)-
+      ;;
+    *)
+      echo "Invalid flags" >&2
+      exit 1
   esac
 done
 
 shift $((OPTIND - 1))
 
 project_name=$1
-project_path="$P_DIR/$project_name"
+project_path="$P_DIR/$tmp_prefix$project_name"
 
 if [[ -z "$project_name" ]]; then
   echo "Error: Please enter a project name" >&2
