home-setup now syncs selected directories

diff --git a/home-setup b/home-setup
--- a/home-setup
+++ b/home-setup
@@ -2,7 +2,23 @@
 
 # Check Dropbox dir exists
 DBOX="$HOME/.dbox/Dropbox"
-[ -d "$DBOX" ] || { echo "Dropbox folder does not exist, please create it at: $DBOX" >&2; exit 1; }
+[ -d "$DBOX" ] || { echo "$(basename $0): Dropbox folder does not exist, please create it at: $DBOX" >&2; exit 1; }
+
+# Setup directories in home dir
+for dir in $(cat dirs-to-sync); do
+    dbox_dir="$DBOX/$dir"
+    dbox_dir_canon=$(readlink -e "$dbox_dir")
+    target="$HOME/$dir"
+    if [ -L "$dbox_dir" -a "$dbox_dir_canon" = "$target" ]; then
+        : # Success, do nothing
+    elif [ -d "$dbox_dir" -a ! -e "$target" ]; then
+        #TODO: wait here
+       mv -b "$dbox_dir" "$target" && \
+           ln -sv "$target" "$dbox_dir"
+    else
+        echo "$(basename $0): Could not process directory: \"$dir\"" >&2
+    fi
+done
 
 # Create symlinks to all dotfiles (in home dir), also add dot to their names
 for file in dotfiles/*; do
